# Generated by Django 5.2 on 2025-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('genre', models.TextField(max_length=250)),
                ('releaseDate', models.IntegerField()),
            ],
        ),
    ]
